{% set name = "fps-login" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_login-{{ version }}.tar.gz
  sha256: 4b796b515dd9f45818f9199cc744e04ebb61f54c5d6cd3366e5ee8ceee05fae6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.9.0,<0.10.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_login

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  summary: An FPS plugin for the login API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
