{% set name = "fps-login" %}
{% set version = "0.0.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_login-{{ version }}.tar.gz
  sha256: a9db3801291336b0708ddf1b75671cb682adfd845126b91ef9a3c6bbf09e025d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.8,<1.0.0

test:
  imports:
    - fps_login

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  summary: An FPS plugin for the login API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
