{% set name = "fps-login" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_login-{{ version }}.tar.gz
  sha256: a1ffc4c292932d8394118cd4efca650fad398824e924c7fc3d6b1a0495693ebe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.13.0,<0.14.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_login

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  summary: An FPS plugin for the login API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
