{% set name = "fps-login" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_login-{{ version }}.tar.gz
  sha256: 13c922f43d2a5062d348b7e4ca235e27cb8d8796259aa4bf54fbfdbf903d012c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.11.0,<0.12.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_login

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  summary: An FPS plugin for the login API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/login
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
